INSERT INTO questions (title, difficulty, expected_topics, time_limit_minutes) VALUES
('Design Twitter Timeline', 'Senior', ARRAY['Fanout-on-Write', 'Fanout-on-Read', 'Celebrity Problem', 'Redis Timeline Cache', 'Snowflake ID', 'Message Broker'], 45),
('Design a Distributed Web Crawler', 'Senior', ARRAY['URL Frontier', 'Bloom Filter', 'Politeness & DNS Caching', 'SimHash Deduplication', 'Robots.txt Parser'], 45),
('Design Google Drive / Dropbox Sync', 'Staff', ARRAY['Chunking (Rabin Fingerprint)', 'Content-Addressable Storage', 'Delta Sync Engine', 'Metadata Sync', 'Conflict Resolution'], 45),
('Design Flash Sale / High-Concurrency Ticketing', 'Senior', ARRAY['Virtual Waiting Room', 'Redis Lua Atomic Reservation', 'Distributed Locks', 'Pessimistic vs Optimistic Locking', 'Idempotency Keys'], 45),
('Design Distributed Key-Value Store (Dynamo)', 'Staff', ARRAY['Consistent Hashing', 'Quorum Replication (W+R>N)', 'Vector Clocks', 'Gossip Protocol', 'Merkle Trees', 'Hinted Handoff'], 45),
('Design Proximity Service / Google Maps', 'Senior', ARRAY['Geohash', 'QuadTree', 'Google S2 Geometry', 'Spatial Indexing', 'Redis GEO', 'Routing Engine'], 45),
('Design Real-Time Top-K / Trending Topics', 'Senior', ARRAY['Count-Min Sketch', 'Heavy Hitters (Space-Saving)', 'Sliding Window Aggregation', 'Flink/Kafka Streams', 'Cache Invalidation'], 45),
('Design Distributed Notification Service', 'Intermediate', ARRAY['Multi-channel Fanout', 'Priority Queuing', 'APNs/FCM Integration', 'Message Deduplication', 'Rate Limiting'], 45)
ON CONFLICT DO NOTHING;

INSERT INTO quiz_decks (id, title, description, difficulty, question_count, est_minutes, category, icon_name)
VALUES 
('deck-social-feeds', 'Social Feeds & High-Fanout Systems', 'Master Fanout-on-Write vs Read, Celebrity problem mitigations, and timeline caching.', 'senior', 2, 8, 'Distributed Architecture', 'Share2'),
('deck-storage-systems', 'Distributed Storage & Key-Value Engines', 'Explore Consistent Hashing, Quorum consensus, Vector Clocks, and Chunking engines.', 'staff', 2, 10, 'Storage & Databases', 'Database'),
('deck-geo-systems', 'Geospatial Indexing & Location Services', 'Compare Geohash, QuadTrees, S2 Geometry, and high-throughput real-time tracking.', 'senior', 2, 8, 'Data Structures & Algorithms', 'MapPin')
ON CONFLICT (id) DO NOTHING;

INSERT INTO quiz_questions (deck_id, question, scenario, topic_tag, options, is_daily)
VALUES
('deck-social-feeds', 'When designing a Twitter/X News Feed, why is pure Fanout-on-Write (Push model) catastrophic for celebrity accounts with 50M+ followers?', 'A celebrity user posts a tweet, triggering background worker jobs to deliver the tweet ID into follower feed inboxes.', 'Social Feed Design', '[{"id": "sf-q1-o1", "text": "Writing 50M records into Redis cache per tweet causes massive write amplification and worker starvation.", "is_correct": true, "explanation": "For high-follower accounts, pushing to millions of timelines causes write bottlenecks. A hybrid model (Fanout-on-Write for normal users, Fanout-on-Read on demand for celebrities) resolves this."}, {"id": "sf-q1-o2", "text": "Celebrity tweets cannot be indexed by relational databases.", "is_correct": false, "explanation": "Relational databases can index records; the bottleneck is memory writes and queuing volume across millions of timeline caches."}]'::jsonb, TRUE),
('deck-social-feeds', 'What is the primary benefit of Twitter Snowflake IDs compared to standard auto-incrementing integers or random UUIDv4s?', 'Generating globally unique primary keys across a distributed sharded database without a central coordinator.', 'Distributed ID Generation', '[{"id": "sf-q2-o1", "text": "Snowflake IDs are 64-bit integers roughly time-ordered, fitting into indexed numeric columns without B-Tree fragmentation.", "is_correct": true, "explanation": "Snowflake IDs encode timestamp (41-bit), worker ID (10-bit), and sequence number (12-bit), yielding compact 64-bit IDs that preserve chronological index locality."}, {"id": "sf-q2-o2", "text": "Snowflake IDs automatically eliminate all database replication lag.", "is_correct": false, "explanation": "ID generation does not solve replication lag."}]'::jsonb, FALSE),
('deck-storage-systems', 'In an AP distributed storage engine (Amazon Dynamo), what purpose do Merkle Trees serve during background Anti-Entropy processes?', 'Replicas periodically synchronize data to repair divergent partitions.', 'Distributed Anti-Entropy', '[{"id": "st-q1-o1", "text": "Hierarchical hash trees allow replicas to compare key ranges and detect differences with minimal network bandwidth.", "is_correct": true, "explanation": "Merkle trees hash sub-branches of keys. Replicas compare root hashes first; if identical, no data transfer is needed. If different, they traverse down only mismatched branches."}, {"id": "st-q1-o2", "text": "Merkle trees enforce ACID transactions across multi-datacenter clusters.", "is_correct": false, "explanation": "Merkle trees are for anti-entropy data sync, not distributed locking or 2PC."}]'::jsonb, TRUE),
('deck-geo-systems', 'How does Geohash enable fast bounding box proximity queries in standard B-Tree indexed databases?', 'Querying nearby restaurants within a 5km radius from a user location.', 'Geospatial Indexing', '[{"id": "geo-q1-o1", "text": "Geohash interleaves latitude and longitude bits into base32 strings where spatial proximity corresponds to common string prefixes.", "is_correct": true, "explanation": "Locations sharing the same geographic grid share matching Geohash prefixes, enabling fast 1D range scans (e.g. WHERE geohash LIKE ''9q8yy%'') in traditional SQL/NoSQL B-Trees."}, {"id": "geo-q1-o2", "text": "Geohash computes exact driving distances using GPU acceleration.", "is_correct": false, "explanation": "Geohash is a spatial indexing system for bounding boxes, not a road routing engine."}]'::jsonb, FALSE)
ON CONFLICT DO NOTHING;
