[tool.poetry]
name = "ai-engine"
version = "0.1.0"
description = "Python AI Engine"
authors = ["Monu Chaudhary <monuchaudharypoonia@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
pydantic-settings = "^2.2.1"
langchain = "^0.1.16"
langchain-community = "^0.0.34"
langchain-groq = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"