from typing import Protocol, Dict, Any, List

class LLMClient(Protocol):
    async def ainvoke(self, input: str) -> Any:
        ...

class InterviewRepository(Protocol):
    def get_interview_context(self, session_id: str) -> Dict[str, Any] | None:
        ...
    def get_diagram_context(self, session_id: str) -> Dict[str, Any] | None:
        ...
    def save_evaluation_report(self, session_id: str, score: int, feedback: Dict[str, Any]) -> None:
        ...
    def save_evaluation_error(self, session_id: str, error_message: str) -> None:
        ...
